package tile;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Armchair.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class Armchair extends Tile {
}
