package tile;
import animal.Animal;
import def.Logger;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entry.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class Entry extends Tile {
	
	public void Add(Animal a) {
		Logger.get_static_logger().enter(this, "Add", new Object[] {a});
		
		a.SetTile(this);
		myAnimal=a;
		a.Exit();
		
		Logger.get_static_logger().exit(this, "Add", new Object[] {a}, "");
	}
}
