package tile;
import animal.Animal;
import def.Logger;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Exit.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class Exit extends Tile {
	private Entry entry;
	
	public boolean Accept(Animal a) {
		Logger.get_static_logger().enter(this, "Accept", new Object[] {a});
		
		// Nem kell leellenrizni, hogy áll-e rajta valaki, mivel olyan nem fordulhat elõ
		a.Move(entry);
		
		Logger.get_static_logger().exit(this, "Accept", new Object[] {a}, "");
		
		return true;
	}
	
	public void setEntry(Entry en) {
		entry = en;
	}
}
