package tile;
import animal.Animal;
import def.Logger;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SlotMachine.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class SlotMachine extends Tile {
	public void Step() {
		Logger.get_static_logger().enter(this, "Step", null);
		
		// random kell csilingelnie, most (skeletonban) minden esetben csilingel
		for (Tile t : neighbours) {
			t.getAnimal().ReactToJingle();
		}
		
		Logger.get_static_logger().exit(this, "Step", null, "");
	}
	
	public boolean Accept(Animal a) {
		return true; //hogy ne dobjon errort
	}
}
