package tile;
import animal.Animal;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VendingMachine.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class VendingMachine extends Tile {
	public void Step() {
	}
	
	public boolean Accept(Animal a) {
		return true; //hogy ne dobjon errort
	}
}
