package tile;
import animal.Animal;
import def.Logger;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WeakTile.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//



public class WeakTile extends Tile {
	public int Count;

	public void Step() {
	}
	
	public Tile[] GetNeighbours() {
		Logger.get_static_logger().enter(this, "GetNeighbours", null);
		Logger.get_static_logger().exit(this, "GetNeighbours", null, "super.neighbours");
		return super.GetNeighbours();
	}
	
	public boolean Accept(Animal a) {
		Logger.get_static_logger().enter(this, "Accept", new Object[] {a});
		
		if(super.getAnimal() == null) {
			a.Move(this);
		} else {
			super.getAnimal().HitBy(a);
		}
		
		Logger.get_static_logger().exit(this, "Accept", new Object[] {a}, "true");
		
		return true;
	}
	
	public void Remove() {
	}
	
	public Animal getAnimal() {
		return super.getAnimal();
	}
	
	public void DecreaseCount() {
		Count--;
	}
	public void Add(Animal a) {
		Logger.get_static_logger().enter(this, "Add", new Object[] {a});
		
		a.SetTile(this);
		myAnimal=a;
		
		DecreaseCount();
		if(Count == 0)
			a.Die();
		
		Logger.get_static_logger().exit(this, "Add", new Object[] {a}, "");
	}
	
	// Skeletonhoz
	// Be kell tudni allitani, hogy mennyi az elete
	public void set_count(int cnt) { this.Count = cnt; }
}
