//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Animal.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//


public abstract class Animal implements Steppable {
	private Tile myTile;
	private Panda follower;
	public void Die() {
	}
	
	public void ReactToJingle() {
	}
	
	public void ReactToBeep() {
	}
	
	public void Exit() {
	}
	
	public void SetTile(Tile t) {
	}
	
	public void Move(Tile t) {
		myTile.Remove();
		follower.Move(myTile);
		t.Add(this);
	}
	
	public void CollideWith(Orangutan o) {	
	}
	
	public void CollideWith(Panda p) {
	}
	
	public void HitBy(Animal a) {
	}
	
	public void TakeASeat(Armchair a) {
		
	}
}
