//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Animal.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public abstract class Animal implements Steppable {
	private Tile myTile;
	private Panda follower;
	public void Die() {
	}
	
	public void ReactToJingle() {
	}
	
	public void ReactToBeep() {
	}
	
	public boolean Exit() {
	}
	
	public void SetTile(Tile t) {
	}
}
