//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entry.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class Entry extends Tile {
	public boolean Accept(Animal a) {
		return true; //hogy ne dobjon errort
	}
}
