//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Exit.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class Exit extends Tile {
	private Entry entry;
	public boolean Accept(Animal a) {
		return true; //hogy ne dobjon errort
	}
}
