//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Orangutan.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class Orangutan extends Animal {
	private Tile myTile;
	private Panda follower;
	
	public void Step() {}
	
	public void HitBy(Animal a) {
		a.CollideWith(this);
	}
	
	public void Die() {
		//Vége a játéknak
	}
	
	public void CollideWith(Orangutan o) {	
	}
	
	public void CollideWith(Panda p) {
		myTile.Add(p);
		//orángutánnak kéne továbblépni, de hova?
		this.follower=p;
		p.DisableSteps();
	}
}
