//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Orangutan.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class Orangutan extends Animal {
	public void Step() {
	}
	
	public void Move() {
	}
}
