//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Panda.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class Panda extends Animal {
	private boolean canStep;
	private Tile myTile;
	private Panda follower;
	
	public void Die() {
		myTile.Remove();
	}
	
	public void Step() {
		Tile[] neighbours=myTile.GetNeighbours();
		Tile t2=neighbours[0];
		t2.Accept(this); //random válaszottam ki a 0.-t
		this.Move(t2);
		
	}
	
	public void Follow(Object Tile) {
	}
	
	public void Let() {
	}
	
	public void Grab(Panda p) {
	}
	
	public void EnableSteps() {
		
	}
	
	public void DisableSteps() {
		
	}
	
	public void HitBy(Animal a) {
		a.CollideWith(this);
	}
	
	public void CollideWith(Orangutan o) {	
	}
	
	public void CollideWith(Panda p) {
	}
	
	public void Exit() {
		
	}
}
