//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Panda.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class Panda extends Animal {
	private boolean isPulled;
	public void Step() {
	}
	
	public void Follow(Object Tile) {
	}
	
	public void Let() {
	}
	
	public void Grab(Panda p) {
	}
}
