//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ShyPanda.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class ShyPanda extends Panda {
	public void ReactToJingle() {
	}
}
