//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SlotMachine.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class SlotMachine extends Tile {
	public void Step() {
	}
	
	public boolean Accept(Animal a) {
	}
}
