//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Steppable.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public interface Steppable {
	public default void Step() {
	}
}
