//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Storey.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class Storey {
	private Tile tiles;
	private Animal animals;
	public void Generate() {
	}
	
	public void Set() {
	}
}
