//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tile.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class Tile implements Steppable {
	private Tile[] neighbours;
	private Animal myAnimal;
	public void Step() {
	}
	
	public Tile[] GetNeighbours() {
		return neighbours;
	}
	
	public void SetNeighbours(Tile[] t) {
		neighbours=t;
	}
	
	public boolean Accept(Animal a) {
		if(myAnimal==null)
			a.Move(this);
		
		else {
			myAnimal.HitBy(a);
		}
		
		return true;
	}
	
	public void Add(Animal a) {
		a.SetTile(this);
	}
	
	public void Remove() {
	}
	
	public Animal getAnimal() {
		return myAnimal;
	}
}
