//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WeakTile.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class WeakTile extends Tile {
	public int Count;
	public boolean Accept(Animal a) {
	}
}
