package animal;
import def.Steppable;
import tile.Armchair;
import tile.Tile;
import def.Logger;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Animal.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//
import java.util.Random;

public abstract class Animal implements Steppable {
	protected Tile myTile;
	protected Panda follower;
	
	public Animal() {
		myTile=null;
		follower=null;
	}
	
	public void Die() {}
	
	public void Step() {}
	
	public void ReactToJingle() {}
	
	public void ReactToBeep() {}
	
	public void Exit() {}
	
	public void SetTile(Tile t) {
		Logger.get_static_logger().enter(this, "SetTile", new Object[] {t});
		
		myTile=t;
		
		Logger.get_static_logger().exit(this, "SetTile", new Object[] {t}, "");
	}
	
	public void Move(Tile t) {
		Logger.get_static_logger().enter(this, "Move", new Object[] {t});
		
		myTile.Remove();
		if (follower != null)
			follower.Move(myTile); 
		t.Add(this);
		
		Logger.get_static_logger().exit(this, "Move", new Object[] {t}, "");
	}
	
	public void Grab(Panda p) {
		Logger.get_static_logger().enter(this, "Grab", new Object[] {p});
		
		this.follower = p;
		
		Logger.get_static_logger().exit(this, "Grab", new Object[] {p}, "");
	}
	
	public void CollideWith(Orangutan o) {}
	
	public void CollideWith(Panda p) {}
	
	public void HitBy(Animal a) {}
	
	public void TakeASeat(Armchair a) {}
}
