package animal;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LazyPanda.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//

import def.Logger;
import tile.Armchair;

public class LazyPanda extends Panda {
	public void TakeASeat(Armchair a) {
		Logger.get_static_logger().enter(this, "TakeASeat", null);
		
		Move(a);
		
		Logger.get_static_logger().exit(this, "TakeASeat", null, "");
	}
}
