package animal;
import java.util.Random;

import def.Logger;
import tile.Tile;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Orangutan.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class Orangutan extends Animal {
	
	public void Step() {
		Logger.get_static_logger().enter(this, "Step", null);
		Tile[] neighbours=myTile.GetNeighbours();
		Random rand=new Random();
		int index=rand.nextInt(neighbours.length);
		
		Tile t=neighbours[index];
		t.Accept(this);
		Logger.get_static_logger().exit(this, "Step", null, "");
	}
	
	public void HitBy(Animal a) {
		Logger.get_static_logger().enter(this, "HitBy", new Object[] {a});
		a.CollideWith(this);
		Logger.get_static_logger().exit(this, "HitBy", new Object[] {a}, "");
	}
	
	public void Die() {
		Logger.get_static_logger().enter(this, "Die", null);
		//Vége a játéknak
		Logger.get_static_logger().exit(this, "Die", null, "");
	}
	
	public void CollideWith(Orangutan o) {	
	}
	
	public void CollideWith(Panda p) {
		Logger.get_static_logger().enter(this, "CollideWith", new Object[] {p});
		myTile.Add(p);
		p.Grab(this.follower);
		this.follower=p;
		p.DisableSteps();
		Logger.get_static_logger().exit(this, "CollideWith", new Object[] {p}, "");
	}
}
