package tile;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cupboard.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class Cupboard extends Tile {
	public void Step() {
	}
}
