package animal;
import def.Steppable;
import tile.Armchair;
import tile.Tile;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Animal.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//
import java.util.Random;

public abstract class Animal implements Steppable {
	protected Tile myTile;
	protected Panda follower;
	
	public void Die() {}
	
	public void Step() {
		Tile[] neighbours=myTile.GetNeighbours();
		Random rand=new Random();
		int index=rand.nextInt(neighbours.length);
		
		Tile t=neighbours[index];
		t.Accept(this);
	}
	
	public void ReactToJingle() {}
	
	public void ReactToBeep() {}
	
	public void Exit() {}
	
	public void SetTile(Tile t) {
		myTile=t;
	}
	
	public void Move(Tile t) {
		myTile.Remove();
		follower.Move(myTile);
		t.Add(this);
		this.SetTile(t);
	}
	
	public void CollideWith(Orangutan o) {}
	
	public void CollideWith(Panda p) {}
	
	public void HitBy(Animal a) {}
	
	public void TakeASeat(Armchair a) {}
}
