package animal;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : HungryPanda.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class HungryPanda extends Panda {
	public void ReactToBeep() {
	}
}
