package animal;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LazyPanda.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//




public class LazyPanda extends Panda {
}
