package animal;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LazyPanda.java
//  @ Date : 2019. 03. 20.
//  @ Author : 
//
//

import tile.Armchair;

public class LazyPanda extends Panda {
	public void TakeASeat(Armchair a) {
		Move(a);
	}
}
